services:
    composer:
        image: composer:latest
        working_dir: /app
        command: sh -c "cd /app && composer update --prefer-dist"
        volumes:
            - ./:/app/:rw

    application:
        build:
            dockerfile: ./docker/application/Dockerfile
            context: .
        working_dir: /app
        environment:
            XDEBUG_MODE: "debug,coverage,develop"
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=application"
        command: tail -f >/dev/null
        depends_on:
            -   composer
        volumes:
            - ./:/app/:rw

    unoserver:
        build:
            dockerfile: ./docker/unoserver/Dockerfile
            context: .
        ports:
            - 2003:2003
        volumes:
            - ./cache/:/data/:rw
